[package]
name = "t-rex"
version = "0.7.3"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"

[dependencies]
toml = "*"
postgres = "*"
fallible-iterator = "*"
r2d2 = "*"
r2d2_postgres = "*"
postgis = "~0.4.0"
protobuf = "*"
nickel = "*"
hyper = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
rustc-serialize = "*"
clap = "*"
log = "*"
env_logger = "*"
time = "*"
flate2 = "*"
pbr = "*"
open = "*"
