[package]
name = "t-rex"
version = "0.8.2-dev"
description = "vector tile server"
repository = "https://github.com/t-rex-tileserver/t-rex"
readme = "README.md"
license = "MIT"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"
path = "src/main.rs"
doctest = false

[dependencies]
t-rex-core = { path = "t-rex-core" }
t-rex-gdal = { path = "t-rex-gdal", optional = true }
t-rex-service = { path = "t-rex-service" }
t-rex-webserver = { path = "t-rex-webserver" }
clap = "*"
log = "*"
env_logger = "*"
time = "*"

[features]
default = ["with-gdal"]
with-gdal = ["t-rex-gdal"]

[workspace]
