[package]
name = "t-rex"
version = "0.6.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"

[features]
dbtest = []

[dependencies]
toml = "*"
r2d2 = "*"
r2d2_postgres = "~0.10.1"
postgis = { git = "https://github.com/pka/rust-postgis.git", branch = "rust-geo" }
protobuf = "*"
nickel = "~0.8.1"
rustc-serialize = "*"
clap = "~2.10.0" # Compile error in 2.11.3
log = "*"
env_logger = "*"
time = "*"
flate2 = "*"
pbr = "*"

[dependencies.postgres]
version = "~0.11.11"
#Breaks Windows build (https://github.com/rust-lang/cargo/issues/2589#issuecomment-224697180)
#features = ["unix_socket"]

[dependencies.hyper]
version = "0.8.1" # Same version as nickel
default-features = false
