[package]
name = "t-rex"
version = "0.0.0"
authors = ["Pirmin Kalberer <pka@sourcepole.ch>"]

[[bin]]
name = "t_rex"

[features]
dbtest = []

[dependencies]
toml = "*"
postgis = "*"
protobuf = "*"
nickel = "*"
nickel_mustache = "*"
rustc-serialize = "*"
clap = "*"
log = "*"
env_logger = "*"
time = "*"
flate2 = "*"

[dependencies.postgres]
version = "*"
#Breaks Windows build (https://github.com/rust-lang/cargo/issues/2589#issuecomment-224697180)
#features = ["unix_socket"]

[dependencies.hyper]
version = "0.8.1"
default-features = false
